name: Snyk Security Scan
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Snyk Security Scan
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects
          
#      - name: Install Snyk
#        run: npm install -g snyk


 #     - name: Debug Snyk Installation
 #       run: snyk --version

#      - name: Authenticate Snyk using CLI
#        run: snyk auth || echo "Please complete Snyk authentication via browser"

#     - name: Snyk scan
#       run: snyk test || echo "Snyk test failed"
       
